### ISSUE TITLE
 Transaction page - Add new transaction 

### ISSUE THREAD

**Issue by kamalsaleh2** [entaxy-project/entaxy#101]
Steps to reproduce
1. Navigate to Portfolio page from the Landing page my clicking "Portfolio" blue link arrow 
2. User should click on top header "Transaction" to navigate to transactions page 
3. Click on '+' button to add a new transaction 
4. User input's values required for Source, Account, Ticker, Shares, Book Value and Date

Expected behavior
1. Data should be validated for all input fields (Source, Account, Ticker, Shares, Book Value, Date) for adding a new transaction by the user
2. Invalid data should prompt an error on the screen to indicate to the user that the data they have input cannot be accepted 
2. Field length must be set for Source, Account, Ticker, Shares, Book Value, Date
3. Book Value and Shares should be integer values only 
4. Date should be set to date value (value for exceeds 4 digits)

Actual behavior
1. All input fields (Source, Account, Ticker, Shares, Book Value, Date) have no defined field length 
2. User can Input negative value for the input fields (Source, Account, Ticker, Shares, Book Value) 
3. Input value for Year (YYYY) in Date field can exceed 4 digits 
4. No validation of user input 
5. No error is prompted when user inputs invalid data 
6. All fields are manually entered but there is no third party validation 

 Screenshot
![entaxy_bug_portfoliotransactions](https://user-images.githubusercontent.com/32586667/45242915-75358080-b2b7-11e8-9430-832dedf02840.jpg)

**Comment by JackNeto** [comment]
Fixed in https://github.com/entaxy-project/entaxy/commit/6d4c795e7f2542d628269dc3f1c6ef956b5335e0
