### ISSUE TITLE
Portfolio links

### ISSUE THREAD

**Issue by JackNeto** [entaxy-project/entaxy#23]
https://docs.google.com/spreadsheets/d/1T3ZTcSph9Ezi9SwkL4CwhltUvM5kCWs5PRCKb9Oki_g/edit#gid=0

http://canadiancouchpotato.com/2012/03/15/a-spreadsheet-to-manage-multiple-accounts/
[CPM-Rebalance-Your-Portfolio-2017.xlsx](https://github.com/entaxy-project/bean-counter/files/1885929/CPM-Rebalance-Your-Portfolio-2017.xlsx)

http://www.canadianportfoliomanagerblog.com/calculators/

https://docs.google.com/spreadsheets/d/1iRqirHYDlpN050PcjmE8y2fQWsPwxtWvv6ojELqRb-A/edit#gid=416704524

https://cubeupload.com/im/wwrgmR.png

**Comment by billxinli** [comment]
Questrade has read only apis that one can tap into for loading portfolios
