### ISSUE TITLE
Contributing standards

### ISSUE THREAD

**Issue by billxinli** [entaxy-project/entaxy#25]
I propose for a standard of contribution to be voted for, specifically:

- CI choice (Travis?)
-- Push to production on successful CI build pipeline
- File name convention, I see camelCase, CapitalCase, and kabab-case in the code. 
- Code standard. Should we use eslint from a known source? Such as AirBnB? I see there is an attempt at: https://github.com/entaxy-project/bean-counter/tree/feature/add-support-flow-eslint-snapshot-test Or should we use Standard.js? 
- Commit standard? (https://github.com/commitizen/cz-cli)
For example:
```
feat(widget): RRSP widget
- Fixed RRSP widget to allow deductions to carry over
- Added checkbox for spousal contribution
```
- package.json postinstall git commit hooks to ensure test && linter passes. 
-- Extension we can hook up `nsp` for code security check

**Comment by JackNeto** [comment]
Ok, instead of starting from scratch I'll move this repo to where it should be.

**Comment by JackNeto** [comment]
> CI choice (Travis?)
> -- Push to production on successful CI build pipeline

Travis yes, push to production on successful CI build no, I'd prefer to deploy to production at specific release points

> File name convention, I see camelCase, CapitalCase, and kabab-case in the code.

👍 

> Code standard. Should we use eslint from a known source? Such as AirBnB? I see there is an attempt at: https://github.com/entaxy-project/bean-counter/tree/feature/add-support-flow-eslint-snapshot-test Or should we use Standard.js?

I'm cool with AirBnb's eslint. 

> Commit standard? (https://github.com/commitizen/cz-cli)

Haven't used this before but looks useful, I like it.

> package.json postinstall git commit hooks to ensure test && linter passes.
> -- Extension we can hook up nsp for code security check

Also haven't used this before, I like it. Lets do it

**Comment by JackNeto** [comment]
- [ ] Setup Travis CI
- [x] Code standard - AIrBnb
- [ ] Commit standard (https://github.com/commitizen/cz-cli)
- [x] package.json postinstall
- [ ] Code security check
