### ISSUE TITLE
Budget links

### ISSUE THREAD

**Issue by JackNeto** [entaxy-project/entaxy#28]
This will help us build a good budget tool in the future:
https://www.reddit.com/r/PersonalFinanceCanada/comments/8c7gn1/i_built_a_spreadsheet_to_track_my_budget_and/?st=jg0rtb13&sh=7b5650d4

Some instructions here: http://themeasureofaplan.com/2018/04/12/budget-tracking-tool/

**Comment by billxinli** [comment]
A lot of people will also use YNAB, and Mint for budgeting.
